name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  cross:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout crystal
      uses: actions/checkout@v3
      with:
        repository: crystal-lang/crystal
        ref: 1.4.1
        path: crystal
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: 1.4.1
    - name: Cross-compile crystal.o
      run: gmake target=x86_64-unknown-dragonfly
      working-directory: crystal
    - name: "marvinpinto/action-automatic-release@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          crystal/.build/crystal.o
